/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aufgabe10_ChatProgramm.View;

/**
 *
 * @author JS
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        rbtnServer = new javax.swing.JRadioButton();
        rbtnClient = new javax.swing.JRadioButton();
        btnConnect = new javax.swing.JButton();
        btnGroupServerClient = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnSend = new javax.swing.JButton();
        grafikFrame = new Aufgabe10_ChatProgramm.View.GrafikFrame();
        lblHeadline = new javax.swing.JLabel();

        jOptionDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jOptionDialog.setTitle("Teilenhmer Auswahl");
        jOptionDialog.setAlwaysOnTop(true);
        jOptionDialog.setModal(true);
        jOptionDialog.setSize(new java.awt.Dimension(350, 250));
        jOptionDialog.getContentPane().setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Teilnehmerart auswählen");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jOptionDialog.getContentPane().add(jLabel2);
        jLabel2.getAccessibleContext().setAccessibleName("Teilnehmer Auswählen");

        btnGroupServerClient.add(rbtnServer);
        rbtnServer.setText("Server");
        rbtnServer.setMargin(new java.awt.Insets(5, 10, 5, 5));
        jOptionDialog.getContentPane().add(rbtnServer);

        btnGroupServerClient.add(rbtnClient);
        rbtnClient.setText("Client");
        rbtnClient.setMargin(new java.awt.Insets(5, 10, 5, 5));
        jOptionDialog.getContentPane().add(rbtnClient);

        btnConnect.setText("Connect");
        jOptionDialog.getContentPane().add(btnConnect);

        jOptionDialog.getAccessibleContext().setAccessibleParent(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Fenster");
        setPreferredSize(new java.awt.Dimension(600, 550));

        btnSend.setText("Senden");
        btnSend.setMargin(new java.awt.Insets(5, 14, 5, 14));
        jPanel1.add(btnSend);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(grafikFrame, java.awt.BorderLayout.CENTER);

        lblHeadline.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHeadline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeadline.setText("Zeichne und erweitere eine Figur");
        lblHeadline.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblHeadline, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.ButtonGroup btnGroupServerClient;
    private javax.swing.JButton btnSend;
    private Aufgabe10_ChatProgramm.View.GrafikFrame grafikFrame;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JDialog jOptionDialog;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeadline;
    private javax.swing.JRadioButton rbtnClient;
    private javax.swing.JRadioButton rbtnServer;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jOptionDialog
     */
    public javax.swing.JDialog getjOptionDialog() {
        return jOptionDialog;
    }

    public javax.swing.JButton getBtnConnect() {
        return btnConnect;
    }

    public void setBtnConnect(javax.swing.JButton btnConnect) {
        this.btnConnect = btnConnect;
    }

    public javax.swing.JRadioButton getRbtnClient() {
        return rbtnClient;
    }

    public void setRbtnClient(javax.swing.JRadioButton rbtnClient) {
        this.rbtnClient = rbtnClient;
    }

    public javax.swing.JRadioButton getRbtnServer() {
        return rbtnServer;
    }

    public void setRbtnServer(javax.swing.JRadioButton rbtnServer) {
        this.rbtnServer = rbtnServer;
    }


    public javax.swing.ButtonGroup getBtnGroupServerClient() {
        return btnGroupServerClient;
    }

    public javax.swing.JButton getBtnSend() {
        return btnSend;
    }

    public GrafikFrame getGrafikFrame() {
        return grafikFrame;
    }

    public javax.swing.JLabel getLblHeadline() {
        return lblHeadline;
    }
}
