/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aufgabe12_CounterBean.TestView;

import Aufgabe12_CounterBean.Model.CounterAbgelaufenEvent;

/**
 *
 * @author JS
 */
public class TestView extends javax.swing.JFrame {

    /**
     * Creates new form TestView
     */
    public TestView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblCounterEvent = new javax.swing.JLabel();
        counterBean1 = new Aufgabe12_CounterBean.CounterBean();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
                btnStartActionPerformed1(evt);
            }
        });
        jPanel1.add(btnStart);

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        jPanel1.add(btnStop);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        lblCounterEvent.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCounterEvent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCounterEvent.setText("Du hast noch Zeit");
        getContentPane().add(lblCounterEvent, java.awt.BorderLayout.PAGE_START);

        counterBean1.addCounterListener(new Aufgabe12_CounterBean.Model.CounterListener() {
            public void counterValueChanged(CounterAbgelaufenEvent evt) {
                counterBean1CounterValueChanged(evt);
            }
        });
        getContentPane().add(counterBean1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStartActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed1
        counterBean1.startCounter();
    }//GEN-LAST:event_btnStartActionPerformed1

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        counterBean1.stopCounter();
    }//GEN-LAST:event_btnStopActionPerformed

    private void counterBean1CounterValueChanged(CounterAbgelaufenEvent evt) {//GEN-FIRST:event_counterBean1CounterValueChanged
        lblCounterEvent.setText("Zeit abgelaufen!");
    }//GEN-LAST:event_counterBean1CounterValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private Aufgabe12_CounterBean.CounterBean counterBean1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCounterEvent;
    // End of variables declaration//GEN-END:variables
}
