/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aufgabe5_CommandDP.View;

/**
 *
 * @author Js-Sc
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fcTableChooser = new javax.swing.JFileChooser();
        pumTable = new javax.swing.JPopupMenu();
        pumiAddRow = new javax.swing.JMenuItem();
        pumiDeleteRow = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnAddRow = new javax.swing.JButton();
        btnDeleteRow = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblOpenFile = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miOpen = new javax.swing.JMenuItem();
        miSave = new javax.swing.JMenuItem();
        mEdit = new javax.swing.JMenu();
        miAddRow = new javax.swing.JMenuItem();
        miDeleteRow = new javax.swing.JMenuItem();
        miDelete = new javax.swing.JMenuItem();

        fcTableChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcTableChooserActionPerformed(evt);
            }
        });
        jPanel1.add(fcTableChooser);

        pumiAddRow.setText("jMenuItem1");
        pumiAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumiAddRowActionPerformed(evt);
            }
        });
        pumTable.add(pumiAddRow);

        pumiDeleteRow.setText("jMenuItem1");
        pumTable.add(pumiDeleteRow);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hauptfenster");
        setPreferredSize(new java.awt.Dimension(980, 720));

        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(10, 10, 5, 5));

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Open24.gif"))); // NOI18N
        btnOpen.setMnemonic('o');
        btnOpen.setToolTipText("Ordner Öffnen ");
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnOpen);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save24.gif"))); // NOI18N
        btnSave.setMnemonic('s');
        btnSave.setToolTipText("Tabelle Speichern");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSave);

        btnAddRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RowInsertAfter24.gif"))); // NOI18N
        btnAddRow.setMnemonic('a');
        btnAddRow.setToolTipText("Zeile EInfügen");
        btnAddRow.setFocusable(false);
        btnAddRow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddRow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAddRow);

        btnDeleteRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RowDelete24.gif"))); // NOI18N
        btnDeleteRow.setMnemonic('x');
        btnDeleteRow.setToolTipText("Zeile Löschen");
        btnDeleteRow.setFocusable(false);
        btnDeleteRow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteRow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDeleteRow);

        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Undo16.gif"))); // NOI18N
        btnUndo.setMnemonic('z');
        btnUndo.setFocusable(false);
        btnUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUndo);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Telefon"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblOpenFile.setText("Geöffnet: ");
        lblOpenFile.setToolTipText("Hier wird der Pfad der Tabelle angezeigt");
        getContentPane().add(lblOpenFile, java.awt.BorderLayout.PAGE_END);

        jMenuBar1.setMargin(new java.awt.Insets(10, 10, 5, 5));

        mFile.setMnemonic('f');
        mFile.setText("File");
        mFile.setToolTipText("");

        miOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Open24.gif"))); // NOI18N
        miOpen.setText("Open");
        miOpen.setToolTipText("Ordner Öffnen ");
        mFile.add(miOpen);

        miSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save24.gif"))); // NOI18N
        miSave.setText("Save");
        miSave.setToolTipText("Tabelle Speichern");
        mFile.add(miSave);

        jMenuBar1.add(mFile);

        mEdit.setMnemonic('e');
        mEdit.setText("Edit");

        miAddRow.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miAddRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RowInsertAfter24.gif"))); // NOI18N
        miAddRow.setText("Insert Row");
        miAddRow.setToolTipText("Zeile Einfügen");
        mEdit.add(miAddRow);

        miDeleteRow.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miDeleteRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RowDelete24.gif"))); // NOI18N
        miDeleteRow.setText("Delete Row");
        miDeleteRow.setToolTipText("Zeile Löschen");
        mEdit.add(miDeleteRow);

        miDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete24.gif"))); // NOI18N
        miDelete.setText("Delete");
        miDelete.setToolTipText("Tabelle Löschen");
        mEdit.add(miDelete);

        jMenuBar1.add(mEdit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fcTableChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcTableChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcTableChooserActionPerformed

    private void pumiAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumiAddRowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pumiAddRowActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUndoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRow;
    private javax.swing.JButton btnDeleteRow;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUndo;
    private javax.swing.JFileChooser fcTableChooser;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblOpenFile;
    private javax.swing.JMenu mEdit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuItem miAddRow;
    private javax.swing.JMenuItem miDelete;
    private javax.swing.JMenuItem miDeleteRow;
    private javax.swing.JMenuItem miOpen;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JPopupMenu pumTable;
    private javax.swing.JMenuItem pumiAddRow;
    private javax.swing.JMenuItem pumiDeleteRow;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fcTableChooser
     */
    public javax.swing.JFileChooser getFcTableChooser() {
        return fcTableChooser;
    }

    public javax.swing.JMenuItem getPumiAddRow() {
        return pumiAddRow;
    }

    public javax.swing.JMenuItem getPumiDeleteRow() {
        return pumiDeleteRow;
    }

    public javax.swing.JTable getjTable1() {
        return jTable1;
    }

    public javax.swing.JLabel getLblOpenFile() {
        return lblOpenFile;
    }

    public void setLblOpenFile(javax.swing.JLabel lblOpenFile) {
        this.lblOpenFile = lblOpenFile;
    }

    public javax.swing.JButton getBtnAddRow() {
        return btnAddRow;
    }

    public javax.swing.JButton getBtnDeleteRow() {
        return btnDeleteRow;
    }

    public javax.swing.JButton getBtnOpen() {
        return btnOpen;
    }

    public javax.swing.JButton getBtnSave() {
        return btnSave;
    }

    public javax.swing.JMenuItem getMiAddRow() {
        return miAddRow;
    }

    public javax.swing.JMenuItem getMiDelete() {
        return miDelete;
    }

    public javax.swing.JMenuItem getMiDeleteRow() {
        return miDeleteRow;
    }

    public javax.swing.JMenuItem getMiOpen() {
        return miOpen;
    }

    public javax.swing.JMenuItem getMiSave() {
        return miSave;
    }

    public javax.swing.JButton getBtnUndo() {
        return btnUndo;
    }

    public void setBtnUndo(javax.swing.JButton btnUndo) {
        this.btnUndo = btnUndo;
    }
}
