/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aufgabe10_ChatProgram.View;

/**
 *
 * @author JS
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        rbtnServer = new javax.swing.JRadioButton();
        rbtnClient = new javax.swing.JRadioButton();
        btnConnect = new javax.swing.JButton();
        btnGroupServerClient = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        taChatView = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        tfChatField = new javax.swing.JTextField();

        jOptionDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jOptionDialog.setTitle("Teilenhmer Auswahl");
        jOptionDialog.setAlwaysOnTop(true);
        jOptionDialog.setModal(true);
        jOptionDialog.setSize(new java.awt.Dimension(350, 250));
        jOptionDialog.getContentPane().setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Teilnehmerart auswählen");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jOptionDialog.getContentPane().add(jLabel2);
        jLabel2.getAccessibleContext().setAccessibleName("Teilnehmer Auswählen");

        btnGroupServerClient.add(rbtnServer);
        rbtnServer.setText("Server");
        rbtnServer.setMargin(new java.awt.Insets(5, 10, 5, 5));
        jOptionDialog.getContentPane().add(rbtnServer);

        btnGroupServerClient.add(rbtnClient);
        rbtnClient.setText("Client");
        rbtnClient.setMargin(new java.awt.Insets(5, 10, 5, 5));
        jOptionDialog.getContentPane().add(rbtnClient);

        btnConnect.setText("Connect");
        jOptionDialog.getContentPane().add(btnConnect);

        jOptionDialog.getAccessibleContext().setAccessibleParent(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Fenster");
        setPreferredSize(new java.awt.Dimension(600, 550));

        taChatView.setColumns(20);
        taChatView.setRows(5);
        jScrollPane1.setViewportView(taChatView);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler1);

        jLabel1.setText("Nachricht:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel1);
        jPanel1.add(filler2);

        tfChatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChatFieldActionPerformed(evt);
            }
        });
        jPanel1.add(tfChatField);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfChatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChatFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.ButtonGroup btnGroupServerClient;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JDialog jOptionDialog;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnClient;
    private javax.swing.JRadioButton rbtnServer;
    private javax.swing.JTextArea taChatView;
    private javax.swing.JTextField tfChatField;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jOptionDialog
     */
    public javax.swing.JDialog getjOptionDialog() {
        return jOptionDialog;
    }

    public javax.swing.JButton getBtnConnect() {
        return btnConnect;
    }

    public void setBtnConnect(javax.swing.JButton btnConnect) {
        this.btnConnect = btnConnect;
    }

    public javax.swing.JRadioButton getRbtnClient() {
        return rbtnClient;
    }

    public void setRbtnClient(javax.swing.JRadioButton rbtnClient) {
        this.rbtnClient = rbtnClient;
    }

    public javax.swing.JRadioButton getRbtnServer() {
        return rbtnServer;
    }

    public void setRbtnServer(javax.swing.JRadioButton rbtnServer) {
        this.rbtnServer = rbtnServer;
    }

    public javax.swing.JTextArea getTaChatView() {
        return taChatView;
    }

    public void setTaChatView(javax.swing.JTextArea taChatView) {
        this.taChatView = taChatView;
    }

    public javax.swing.JTextField getTfChatField() {
        return tfChatField;
    }

    public void setTfChatField(javax.swing.JTextField tfChatField) {
        this.tfChatField = tfChatField;
    }
}
